from flask import render_template, redirect, url_for, flash, request, abort
from flask_login import login_required, current_user
from app.expenses import expenses_bp
from app.expenses.forms import ExpenseForm
from app.models import Expense, ExpenseCategory, Vehicle, Trip, ActivityLog, AuditLog, Notification
from app.extensions import db
from app.utils.decorators import role_required

@expenses_bp.route('/')
@login_required
@role_required('Fleet Manager', 'Financial Analyst')
def index():
    page = request.args.get('page', 1, type=int)
    search_query = request.args.get('search', '', type=str).strip()
    category_filter = request.args.get('category', '', type=str)
    vehicle_filter = request.args.get('vehicle', '', type=str)
    sort_by = request.args.get('sort_by', 'date', type=str)
    sort_order = request.args.get('sort_order', 'desc', type=str)

    query = Expense.query.join(Vehicle).outerjoin(Trip).join(ExpenseCategory)

    if search_query:
        query = query.filter(
            (Expense.description.ilike(f'%{search_query}%')) |
            (ExpenseCategory.name.ilike(f'%{search_query}%')) |
            (Vehicle.registration_number.ilike(f'%{search_query}%')) |
            (Vehicle.name.ilike(f'%{search_query}%'))
        )

    if category_filter:
        query = query.filter(ExpenseCategory.name == category_filter)
    if vehicle_filter:
        query = query.filter(Expense.vehicle_id == vehicle_filter)

    if sort_by == 'registration_number':
        column = Vehicle.registration_number
    elif sort_by == 'trip_code':
        column = Trip.trip_code
    elif sort_by == 'category':
        column = ExpenseCategory.name
    elif hasattr(Expense, sort_by):
        column = getattr(Expense, sort_by)
    else:
        column = Expense.date

    if sort_order == 'desc':
        query = query.order_by(column.desc())
    else:
        query = query.order_by(column.asc())

    pagination = query.paginate(page=page, per_page=10, error_out=False)
    expenses = pagination.items

    vehicles = Vehicle.query.filter(Vehicle.status != 'retired').all()
    categories = ExpenseCategory.query.all()

    return render_template(
        'expenses/index.html',
        expenses=expenses,
        pagination=pagination,
        vehicles=vehicles,
        categories=categories,
        search=search_query,
        category_filter=category_filter,
        vehicle_filter=vehicle_filter,
        sort_by=sort_by,
        sort_order=sort_order
    )

@expenses_bp.route('/create', methods=['GET', 'POST'])
@login_required
@role_required('Fleet Manager', 'Financial Analyst')
def create():
    form = ExpenseForm()
    
    vehicles = Vehicle.query.filter(Vehicle.status != 'retired').all()
    trips = Trip.query.order_by(Trip.created_date.desc()).limit(50).all()
    
    form.vehicle_id.choices = [(v.id, f"{v.registration_number} - {v.name}") for v in vehicles]
    form.trip_id.choices = [(0, '-- None --')] + [(t.id, f"{t.trip_code} ({t.source} to {t.destination})") for t in trips]
    
    if form.validate_on_submit():
        expense = Expense(
            vehicle_id=form.vehicle_id.data,
            trip_id=form.trip_id.data if form.trip_id.data != 0 else None,
            expense_category_id=form.expense_category_id.data,
            amount=form.amount.data,
            description=form.description.data.strip(),
            date=form.date.data
        )
        db.session.add(expense)
        db.session.flush() # get ID
        
        ActivityLog.log_activity(
            action=f"Logged expense under category '{expense.expense_type}' for vehicle {expense.vehicle.registration_number}. Amount: ₹{expense.amount}",
            module="Expenses",
            user_id=current_user.id
        )
        AuditLog.log_audit(
            table_name="expenses",
            row_id=expense.id,
            action_type="INSERT",
            new_value=f"Vehicle: {expense.vehicle.registration_number}, Category: {expense.expense_type}, Cost: {expense.amount}",
            user_id=current_user.id
        )
        
        db.session.commit()
        flash("Expense logged successfully.", "success")
        return redirect(url_for('expenses.index'))
        
    return render_template('expenses/create.html', form=form)

@expenses_bp.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
@role_required('Fleet Manager', 'Financial Analyst')
def edit(id):
    expense = Expense.query.get_or_404(id)
    
    if "Auto-generated" in expense.description:
        flash("This expense was auto-generated by the Fuel or Maintenance modules. Please modify the source record to update it.", "warning")
        if "fuel expense" in expense.description.lower():
            return redirect(url_for('fuel.index'))
        elif "repair expense" in expense.description.lower():
            return redirect(url_for('maintenance.index'))
            
    form = ExpenseForm(obj=expense)
    
    vehicles = Vehicle.query.filter(Vehicle.status != 'retired').all()
    trips = Trip.query.order_by(Trip.created_date.desc()).limit(50).all()
    
    form.vehicle_id.choices = [(v.id, f"{v.registration_number} - {v.name}") for v in vehicles]
    form.trip_id.choices = [(0, '-- None --')] + [(t.id, f"{t.trip_code} ({t.source} to {t.destination})") for t in trips]
    
    if request.method == 'GET':
        form.trip_id.data = expense.trip_id or 0
        
    if form.validate_on_submit():
        old_val = f"Vehicle ID: {expense.vehicle_id}, Category ID: {expense.expense_category_id}, Cost: {expense.amount}"
        
        expense.vehicle_id = form.vehicle_id.data
        expense.trip_id = form.trip_id.data if form.trip_id.data != 0 else None
        expense.expense_category_id = form.expense_category_id.data
        expense.amount = form.amount.data
        expense.description = form.description.data.strip()
        expense.date = form.date.data
        
        ActivityLog.log_activity(
            action=f"Updated expense record #{expense.id} for vehicle {expense.vehicle.registration_number}",
            module="Expenses",
            user_id=current_user.id
        )
        AuditLog.log_audit(
            table_name="expenses",
            row_id=expense.id,
            action_type="UPDATE",
            old_value=old_val,
            new_value=f"Vehicle ID: {expense.vehicle_id}, Category ID: {expense.expense_category_id}, Cost: {expense.amount}",
            user_id=current_user.id
        )
        
        db.session.commit()
        flash("Expense details updated successfully.", "success")
        return redirect(url_for('expenses.index'))
        
    return render_template('expenses/edit.html', form=form, expense=expense)

@expenses_bp.route('/delete/<int:id>', methods=['POST'])
@login_required
@role_required('Fleet Manager', 'Financial Analyst')
def delete(id):
    expense = Expense.query.get_or_404(id)
    if "Auto-generated" in expense.description:
        flash("This expense was auto-generated and cannot be deleted directly. Please delete the source Fuel Log or Maintenance record.", "warning")
        return redirect(url_for('expenses.index'))
        
    ActivityLog.log_activity(
        action=f"Deleted manual expense record #{expense.id} (Category: {expense.expense_type}, Value: ₹{expense.amount})",
        module="Expenses",
        user_id=current_user.id
    )
    AuditLog.log_audit(
        table_name="expenses",
        row_id=expense.id,
        action_type="DELETE",
        old_value=f"Vehicle ID: {expense.vehicle_id}, Category ID: {expense.expense_category_id}, Cost: {expense.amount}",
        user_id=current_user.id
    )
        
    db.session.delete(expense)
    db.session.commit()
    flash("Expense deleted successfully.", "success")
    return redirect(url_for('expenses.index'))
